### ISSUE TITLE
Skriva XML kommentarer på metoder.

### ISSUE THREAD

**Issue by Leon-Hobby** [Group1Fullstackkurs/LinguiniBooks-Backend#40]

**Comment by CGDM101** [comment]
- [x] bookcrud.cs
- [x] passwordhelper
- [x] usercrud
- [x] readconnstring
- [x] BookController
- [x] UserController

**Comment by CGDM101** [comment]
@Leon-Hobby  @Phoenixbird7 Fyll gärna på om det är något mer jag missat, som ska kommenteras.

**Comment by CGDM101** [comment]
Alla är gjorda.
